"""initial migration

Revision ID: 5a13de717975
Revises: 
Create Date: 2025-10-08 08:40:28.322479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a13de717975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption',
    sa.Column('id_consumption', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('smc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_consumption')
    )
    op.create_table('cost',
    sa.Column('id_cost', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('smc', sa.Float(), nullable=False),
    sa.Column('kwh_cost', sa.Float(), nullable=True),
    sa.Column('smc_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_cost')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost')
    op.drop_table('consumption')
    # ### end Alembic commands ###