services:
  energy_web:
    image: manzolo/energy-consumption:latest
    container_name: energy_web
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    #volumes:
    #  - .:/app
    depends_on:
      energy_db:
        condition: service_healthy
    #entrypoint: ["./entrypoint.sh"]
    stdin_open: true
    tty: true

  energy_db:
    image: postgres:15-alpine
    container_name: energy_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5