version: '3'
services:
    app:
        image: manzolo/energy-consumption:latest
        restart: always
        container_name: energy-consumption
        volumes:
            - ./consumption_app/data/consumption.db:/app/consumption_app/data/consumption.db
        ports:
            - "80:8000"
