services:
    app:
        image: manzolo/energy-consumption:latest
        restart: always
        container_name: energy-consumption
        volumes:
            - ./consumption.db:/app/consumption_app/data/consumption.db
        ports:
            - "8000:8000"
